### ISSUE TITLE
Error 923 : "Failure due to: StaleUic" on sendMessage

### ISSUE THREAD

**Issue by mArm-ch** [Kibioctet/SkypePHP#3]
Hi, very nice project.

I use it to write a bot, but when I want to send a direct message, I got this error (added a var_dump in sendMessage()) :
```
array(2) {
  ["errorCode"]=>
  int(923)
  ["message"]=>
  string(25) "Failure due to: StaleUic."
}
```

I can't find any informations about this error. 
Can you try to fix it or give me a link to the api documentation please '

**Comment by Kibioctet** [comment]
sendMessage() works properly with me, and I can't know anything for the error code 923 because there is not any official documentation for the Skype API. Have you tried to send your message from another account ? What message are you trying to send?

**Comment by mArm-ch** [comment]
I simply tried to send "Hello" to my other account in a convesation.

It worked perfectly from some message, then after some sent messages, I got the error described above.

Here the exact line I use 
`$skype->sendMessage(Config::$owner, 'Salut boss, je suis là. ;)');`

**Comment by Kibioctet** [comment]
when you send too many messages, your Skype account can be locked for multiple hours (flood protection), this can be your problem, I think. can you still send any message to someone else from the Skype account of your bot ?

**Comment by mArm-ch** [comment]
No, but I can send message if I connect my bot with another account. I think it's because of my dev tries, I maybe spammed as you say.

Wait and see.
I come back to add infos or close issue

**Comment by mArm-ch** [comment]
Well it was spamming protection. I waited a hour and it's ok now.
Thanks for your time
